apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ec2-${{ values.InstanceName }}
  annotations:
    github.com/project-slug: ${{ values.repo_owner }}/${{ values.repo }}
    backstage.io/techdocs-ref: dir:.
  title: ${{ values.InstanceName }} instance deployment
  description: Deployment ${{ values.InstanceName }} Instance.
spec:
  type: service
  owner: user:guest
  lifecycle: experimental