site_name: ${{ values.InstanceName }}
site_description: ${{ values.description }}
repo_url: https://github.com/${{ values.repo_owner }}/${{ values.repo }}
edit_uri: edit/main/docs

plugins:
  - techdocs-core

# Note for content editors, edit only the section below
nav:
  - ${{ values.InstanceName }} Documentation: index.md